### ISSUE TITLE
meta issue before oss review

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/pyansys-quarto-cheatsheet#4]
- [x] add footer tex
- [x] update fonts and styles
- [x]  define output dir
- [x] add required files
